var annotated_dup =
[
    [ "AJWNU_Actor_ApiTest", "class_a_j_w_n_u___actor___api_test.html", "class_a_j_w_n_u___actor___api_test" ],
    [ "FJWNetworkUtilityModule", "class_f_j_w_network_utility_module.html", "class_f_j_w_network_utility_module" ],
    [ "FJWNetworkUtilityTestModule", "class_f_j_w_network_utility_test_module.html", "class_f_j_w_network_utility_test_module" ],
    [ "FJWNU_AccessTokenContainer", "struct_f_j_w_n_u___access_token_container.html", "struct_f_j_w_n_u___access_token_container" ],
    [ "FJWNU_DummyStruct", "struct_f_j_w_n_u___dummy_struct.html", null ],
    [ "FJWNU_PendingApiRequest", "struct_f_j_w_n_u___pending_api_request.html", "struct_f_j_w_n_u___pending_api_request" ],
    [ "FJWNU_PendingJob", "struct_f_j_w_n_u___pending_job.html", "struct_f_j_w_n_u___pending_job" ],
    [ "FJWNU_RefreshTokenContainer", "struct_f_j_w_n_u___refresh_token_container.html", "struct_f_j_w_n_u___refresh_token_container" ],
    [ "FJWNU_REQ_AuthLogin", "struct_f_j_w_n_u___r_e_q___auth_login.html", "struct_f_j_w_n_u___r_e_q___auth_login" ],
    [ "FJWNU_REQ_AuthRegister", "struct_f_j_w_n_u___r_e_q___auth_register.html", "struct_f_j_w_n_u___r_e_q___auth_register" ],
    [ "FJWNU_REQ_AuthRegisterSendCode", "struct_f_j_w_n_u___r_e_q___auth_register_send_code.html", "struct_f_j_w_n_u___r_e_q___auth_register_send_code" ],
    [ "FJWNU_REQ_AuthRegisterVerifyCode", "struct_f_j_w_n_u___r_e_q___auth_register_verify_code.html", "struct_f_j_w_n_u___r_e_q___auth_register_verify_code" ],
    [ "FJWNU_RequestConfig", "struct_f_j_w_n_u___request_config.html", "struct_f_j_w_n_u___request_config" ],
    [ "FJWNU_RES_AuthRefresh", "struct_f_j_w_n_u___r_e_s___auth_refresh.html", "struct_f_j_w_n_u___r_e_s___auth_refresh" ],
    [ "FJWNU_RES_Base", "struct_f_j_w_n_u___r_e_s___base.html", "struct_f_j_w_n_u___r_e_s___base" ],
    [ "FScopeWallLogger", "struct_f_scope_wall_logger.html", "struct_f_scope_wall_logger" ],
    [ "JWNetworkUtility", "class_j_w_network_utility.html", "class_j_w_network_utility" ],
    [ "JWNetworkUtilityTest", "class_j_w_network_utility_test.html", "class_j_w_network_utility_test" ],
    [ "UJWNU_BFL_ApiClientService", "class_u_j_w_n_u___b_f_l___api_client_service.html", "class_u_j_w_n_u___b_f_l___api_client_service" ],
    [ "UJWNU_BFL_AuthWidget", "class_u_j_w_n_u___b_f_l___auth_widget.html", null ],
    [ "UJWNU_GIS_ApiClientService", "class_u_j_w_n_u___g_i_s___api_client_service.html", null ],
    [ "UJWNU_GIS_ApiHostProvider", "class_u_j_w_n_u___g_i_s___api_host_provider.html", "class_u_j_w_n_u___g_i_s___api_host_provider" ],
    [ "UJWNU_GIS_ApiIdentityProvider", "class_u_j_w_n_u___g_i_s___api_identity_provider.html", "class_u_j_w_n_u___g_i_s___api_identity_provider" ],
    [ "UJWNU_GIS_CustomCodeHelper", "class_u_j_w_n_u___g_i_s___custom_code_helper.html", "class_u_j_w_n_u___g_i_s___custom_code_helper" ],
    [ "UJWNU_GIS_HttpClientHelper", "class_u_j_w_n_u___g_i_s___http_client_helper.html", "class_u_j_w_n_u___g_i_s___http_client_helper" ],
    [ "UJWNU_GIS_HttpRequestJobProcessor", "class_u_j_w_n_u___g_i_s___http_request_job_processor.html", "class_u_j_w_n_u___g_i_s___http_request_job_processor" ],
    [ "UJWNU_GIS_SteamWorks", "class_u_j_w_n_u___g_i_s___steam_works.html", null ],
    [ "UJWNU_HttpRequestJob", "class_u_j_w_n_u___http_request_job.html", "class_u_j_w_n_u___http_request_job" ]
];